#!/bin/bash
# Cloud Sync Script for google_drive
# Generated by Kotlin MCP Server

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$SCRIPT_DIR/sync_config.json"

# Load configuration
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Error: Configuration file not found: $CONFIG_FILE"
    exit 1
fi

# Create required directories
mkdir -p "$SCRIPT_DIR/cache"
mkdir -p "$SCRIPT_DIR/logs"

# Log file
LOG_FILE="$SCRIPT_DIR/logs/sync_$(date +%Y%m%d_%H%M%S).log"

echo "Starting cloud sync at $(date)" | tee "$LOG_FILE"

# Google Drive sync using rclone
if ! command -v rclone &> /dev/null; then
    echo "Error: rclone is required for Google Drive sync"
    echo "Install: https://rclone.org/install/"
    exit 1
fi

# Sync to Google Drive
rclone sync "$PROJECT_DIR" "gdrive:kotlin-projects/$(basename "$PROJECT_DIR")" \
    --include-from "$SCRIPT_DIR/include_patterns.txt" \
    --exclude-from "$SCRIPT_DIR/exclude_patterns.txt" \
    --progress \
    --log-file "$LOG_FILE"

# Apply encryption before sync
echo "Applying encryption..." | tee -a "$LOG_FILE"

echo "Sync completed at $(date)" | tee -a "$LOG_FILE"
